
CREATE DATABASE DeraWebBD;
USE DeraWebBD;

CREATE USER usuarioWeb;
GRANT SELECT,INSERT,UPDATE,DELETE ON * TO usuarioWeb;

CREATE TABLE AREAS_DE_INTERES(
	Nombre_Area VARCHAR (50) NOT NULL,
	AreaID INT,
	PRIMARY KEY (AreaID)
);

CREATE TABLE CURSO(
	Nombre_Curso VARCHAR (20) NOT NULL,
	CursoID INT,
	PRIMARY KEY (CursoID)
);

CREATE TABLE ALUMNO(
	DNI VARCHAR (9) NOT NULL,
	Apellidos VARCHAR (35) NOT NULL,
	Nombre VARCHAR (30) NOT NULL,
	Correo VARCHAR (40) NOT NULL,
	Telefono INT NULL,
	AlumnoID INT,
	PRIMARY KEY (AlumnoID)
);

CREATE TABLE TUTOR(
	Nombre VARCHAR (40) NOT NULL,
	Apellidos VARCHAR (50) NOT NULL,
	TutorID INT,
	PRIMARY KEY (TutorID)
);

CREATE TABLE TIENE(
	AlumnoID INT,
	AreaID INT,
CONSTRAINT fk_AlumnoID_TIENE
	FOREIGN KEY (AlumnoID)
	REFERENCES ALUMNO(AlumnoID) ON DELETE CASCADE,
	CONSTRAINT fk_AreaID_TIENE
	FOREIGN KEY (AreaID)
	REFERENCES AREAS_DE_INTERES(AreaID) ON DELETE CASCADE
);

CREATE TABLE SE_MATRICULA(
	Importe FLOAT NOT NULL,
	Fecha_de_compra DATE NOT NULL,
	AlumnoID INT,
	CursoID INT,
CONSTRAINT fk_AlumnoID_SE_MATRICULA
	FOREIGN KEY (AlumnoID)
	REFERENCES ALUMNO(AlumnoID) ON DELETE CASCADE,
	CONSTRAINT fk_CursoID_SE_MATRICULA
	FOREIGN KEY (CursoID)
	REFERENCES CURSO(CursoID) ON DELETE CASCADE
);

